#!/usr/bin/env python3
"""Emit the two bar-chart figures as pure-LaTeX rule bars.

Every number below is copied verbatim from ../story.md; nothing is derived,
interpolated, or averaged here beyond the bar lengths themselves.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# component, n, prompt tokens, baseline ms, ours ms, oracle ms
ROWS = [
    ("normalize",           20,  193,  37.3,  37.6, 35.3),
    ("route",               20,  549,  65.8,  65.9, 37.8),
    ("Math.analyze",     8,  500,  65.8,  66.1, 37.8),
    ("Code.analyze",     4,  423,  64.0,  64.3, 34.5),
    ("Doc.analyze",      3,  283,  52.3,  52.3, 35.2),
    ("Write.analyze",    5,  294,  52.3,  52.5, 36.6),
    ("Math.solve",       8,  879, 119.8,  67.8, 37.7),
    ("Code.implement",   4,  835, 117.9,  49.7, 36.2),
    ("Doc.answer",       3,  707, 102.3,  62.3, 37.1),
    ("Write.draft",      5,  676, 102.0,  50.7, 37.9),
    ("Math.finalize",    8, 1453, 216.3,  42.7, 40.1),
    ("Code.finalize",    4, 1292, 187.0,  42.6, 37.2),
    ("Doc.finalize",     3, 1296, 185.0,  41.5, 39.2),
    ("Write.finalize",   5, 1258, 171.1,  41.9, 39.6),
]
SUM = ("sum / request", 20, 469.9, 265.1, 186.2)

# call site, baseline ms, ours ms
REACT = [("reason", 39.3, 39.3), ("integrate", 39.4, 38.3), ("finalize", 66.8, 39.2)]

BAR_H = "1.5mm"
GAP = r"\\[0.35mm]"


def bar(width_mm, color):
    w = max(width_mm, 0.15)
    return r"{\color{%s}\rule{%.2fmm}{%s}}" % (color, w, BAR_H)


def triple(label, b, o, orc, scale, bold=False):
    lab = r"\textbf{%s}" % label if bold else label
    out = []
    out.append(r"%s & %s & \scriptsize %.1f \\[0.35mm]" % (lab, bar(b * scale, "cbase"), b))
    out.append(r" & %s & \scriptsize %.1f \\[0.35mm]" % (bar(o * scale, "cours"), o))
    out.append(r" & %s & \scriptsize %.1f \\[1.4mm]" % (bar(orc * scale, "coracle"), orc))
    return "\n".join(out)


def main():
    scale = 26.0 / 216.3  # mm per ms, longest bar = 26mm

    lines = [r"{\footnotesize\setlength{\tabcolsep}{2pt}",
             r"\begin{tabular}{@{}l@{\hspace{3pt}}l@{\hspace{2pt}}l@{}}"]
    for name, _n, _tok, b, o, orc in ROWS:
        lines.append(triple(r"\texttt{\scriptsize %s}" % name.replace("_", r"\_"), b, o, orc, scale))
    lines.append(r"\midrule[0.4pt]")
    lines.append(triple(r"\textbf{\scriptsize %s}" % SUM[0], SUM[2], SUM[3], SUM[4], scale, bold=False))
    lines.append(r"\end{tabular}}")
    lines.append(r"\\[1mm]{\scriptsize"
                 r"{\color{cbase}\rule{3mm}{1.5mm}}~baseline (vLLM APC)\quad"
                 r"{\color{cours}\rule{3mm}{1.5mm}}~\sysname\quad"
                 r"{\color{coracle}\rule{3mm}{1.5mm}}~Oracle\quad(median TTFT, ms)}")
    with open(os.path.join(HERE, "fig_percomponent.tex"), "w") as f:
        f.write("% generated by gen_figures.py from story.md\n" + "\n".join(lines) + "\n")

    scale2 = 26.0 / 66.8
    lines = [r"{\footnotesize\setlength{\tabcolsep}{2pt}",
             r"\begin{tabular}{@{}l@{\hspace{3pt}}l@{\hspace{2pt}}l@{}}"]
    for name, b, o in REACT:
        lines.append(r"\texttt{\scriptsize %s} & %s & \scriptsize %.1f \\[0.35mm]"
                     % (name, bar(b * scale2, "cbase"), b))
        lines.append(r" & %s & \scriptsize %.1f \\[1.4mm]" % (bar(o * scale2, "cours"), o))
    lines.append(r"\end{tabular}}")
    lines.append(r"\\[0.5mm]{\scriptsize"
                 r"{\color{cbase}\rule{3mm}{1.5mm}}~baseline\quad"
                 r"{\color{cours}\rule{3mm}{1.5mm}}~\sysname\quad(median TTFT, ms)}")
    with open(os.path.join(HERE, "fig_react_bars.tex"), "w") as f:
        f.write("% generated by gen_figures.py from story.md\n" + "\n".join(lines) + "\n")

    print("wrote fig_percomponent.tex and fig_react_bars.tex")


if __name__ == "__main__":
    main()
